linters:
    flake8:
        python: 3
        config: ./setup.cfg
        max-line-length: 79
        max-complexity: 20
        fixer: true

    pep8:
        python: 3
        config: ./setup.cfg
        max-line-length: 79
        fixer: true

fixers:
  enable: true
