---
linters:
    black:
        config: ./pyproject.toml
        fixer: true

    flake8:
        python: 3
        config: ./setup.cfg
        max-line-length: 79
        max-complexity: 20
        fixer: true

    pep8:
        python: 3
        config: ./setup.cfg
        max-line-length: 79
        fixer: true

    pytype:
        config: ./setup.cfg
        fixer: true

    py3k:
      ignore: 'W1618,W1655'
      ignore-patterns: 'generated/.*'
